sudo: 'required'

services:
  - 'docker'

language:
  - 'bash'

env:
  matrix:
    - BUILD_FROM=amd64/erlang:21.3-alpine QEMU_ARCH=x86_64 ARCH=amd64
    - BUILD_FROM=arm64v8/erlang:21.3-alpine QEMU_ARCH=aarch64 ARCH=arm64v8
    - BUILD_FROM=arm32v7/erlang:21.3-alpine QEMU_ARCH=arm ARCH=arm32v7
    - BUILD_FROM=i386/erlang:21.3-alpine QEMU_ARCH=i386 ARCH=i386
    - BUILD_FROM=s390x/erlang:21.3-alpine QEMU_ARCH=s390x ARCH=s390x

before_install:
  - sudo make -C ./v3.2 prepare

install: true

script:
  # Build Docker image
  - pushd ./v3.2 && make build && popd

  # Test Docker image
  - make -C ./v3.2 test

  # Push Docker image
  - >
    if [[ ! -z $(echo $EMQX_VERSION | grep -oE "v[0-9]+\.[0-9]+(\.[0-9]+)?") ]]; then
      # Tag Docker image
      make -C ./v3.2 tag

      # Docker Login
      echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      # Push Docker image
      make -C ./v3.2 push

      # Docker Logout
      docker logout
    fi

jobs:
    include:
        - stage: manifest
          if: tag =~ ^v
          script:
              # Docker Login
              - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

              # Create and Push Docker Manifest Lists to Docker Hub
              - echo "Create manifest list for all docker images."
              - make -C ./v3.2 manifest-list

              # Docker Logout
              - docker logout

# notify me when things fail
notifications:
    email: true
